"""Cross-protocol public-key strength scoring.

lodan captures key material in two places — TLS certificate chains and SSH
host keys — and until now judged neither. A 1024-bit RSA host key and a
ROCA-vulnerable modulus were both invisible.

This pass reads the key material already stored (`chain_certs.der` from the
TLS chain work, and the SSH host-key blobs the probe now retains) and scores
it offline. No traffic of any kind: it is arithmetic over public numbers.

Two classes of verdict, deliberately routed to different tables:

- Weak-but-not-a-CVE (RSA<2048, DSA, small curves) is a *posture* judgement
  and goes to `findings`, which is severity-scored and diffable.
- A ROCA hit is a specific advisory, CVE-2017-15361, and goes to `vulns`
  where genuine CVE identifiers live.
"""
from __future__ import annotations

import sqlite3
import struct
from dataclasses import dataclass

ROCA_CVE = "CVE-2017-15361"

_MIN_RSA_BITS = 2048
_MIN_DSA_BITS = 2048
_MIN_EC_BITS = 224


# --- ROCA (CVE-2017-15361) ---------------------------------------------------
#
# Infineon's RSALib generated primes of the form
#
#     p = k*M + (65537^a mod M)
#
# where M is the primorial of the first n primes. Reducing modulo any prime
# p_i dividing M gives p ≡ 65537^a (mod p_i), and since N = p*q,
#
#     N ≡ 65537^(a+b) (mod p_i)
#
# So for a vulnerable key, `N mod p_i` must lie in the cyclic subgroup
# generated by 65537 modulo p_i — for every p_i. That is the standard ROCA
# fingerprint, and it is *derived* here rather than carried as a hardcoded
# table of magic constants, so it can be read and checked rather than trusted.
#
# This is a necessary condition, not a factorization. A random modulus passing
# every prime below is astronomically unlikely but not impossible, which is
# why the emitted vuln row carries a confidence below 1.0 and the finding says
# "fingerprint matches" rather than "is vulnerable".

_ROCA_PRIMES = (
    3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
    73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151,
    157, 163, 167,
)


def _generator_subgroup(prime: int, generator: int = 65537) -> frozenset[int]:
    """Residues reachable as generator^k mod prime."""
    seen: set[int] = set()
    value = 1 % prime
    for _ in range(prime):
        if value in seen:
            break
        seen.add(value)
        value = (value * generator) % prime
    return frozenset(seen)


_ROCA_SUBGROUPS = tuple(
    (prime, _generator_subgroup(prime)) for prime in _ROCA_PRIMES
)


def roca_fingerprint(modulus: int) -> bool:
    """True when `modulus` matches the ROCA fingerprint.

    A necessary condition for Infineon RSALib generation, not proof of it.
    """
    if modulus <= 1:
        return False
    return all(modulus % prime in subgroup for prime, subgroup in _ROCA_SUBGROUPS)


# --- key material extraction -------------------------------------------------


@dataclass(frozen=True)
class PublicKey:
    """A public key lifted from either protocol, normalized."""

    source: str            # "tls-chain" | "ssh-hostkey"
    label: str             # cert subject / SSH algorithm name
    key_type: str          # rsa | dsa | ec | ed25519 | ...
    bits: int | None = None
    curve: str | None = None
    modulus: int | None = None       # RSA only; what ROCA needs
    depth: int | None = None         # TLS chain position


def _ssh_string(buf: bytes, pos: int) -> tuple[bytes, int]:
    if pos + 4 > len(buf):
        raise ValueError("truncated SSH string")
    (length,) = struct.unpack_from(">I", buf, pos)
    pos += 4
    if length > len(buf) - pos:
        raise ValueError("SSH string overruns blob")
    return buf[pos : pos + length], pos + length


def parse_ssh_public_key(blob: bytes) -> PublicKey | None:
    """Parse an SSH wire-format public key blob (RFC 4253 §6.6).

    Hand-rolled rather than routed through asyncssh so the modulus is
    available even when asyncssh isn't installed — and because the blob is
    what we stored, not a live key object.
    """
    try:
        algo_bytes, pos = _ssh_string(blob, 0)
        algo = algo_bytes.decode("ascii", "replace")
        if algo == "ssh-rsa":
            _e, pos = _ssh_string(blob, pos)          # public exponent
            n_bytes, pos = _ssh_string(blob, pos)
            modulus = int.from_bytes(n_bytes, "big")
            return PublicKey(
                source="ssh-hostkey", label=algo, key_type="rsa",
                bits=modulus.bit_length(), modulus=modulus,
            )
        if algo == "ssh-dss":
            p_bytes, pos = _ssh_string(blob, pos)
            return PublicKey(
                source="ssh-hostkey", label=algo, key_type="dsa",
                bits=int.from_bytes(p_bytes, "big").bit_length(),
            )
        if algo.startswith("ecdsa-sha2-"):
            curve_bytes, pos = _ssh_string(blob, pos)
            curve = curve_bytes.decode("ascii", "replace")
            bits = {"nistp256": 256, "nistp384": 384, "nistp521": 521}.get(curve)
            return PublicKey(
                source="ssh-hostkey", label=algo, key_type="ec",
                bits=bits, curve=curve,
            )
        if algo == "ssh-ed25519":
            return PublicKey(
                source="ssh-hostkey", label=algo, key_type="ed25519", bits=256,
            )
        return PublicKey(source="ssh-hostkey", label=algo, key_type=algo)
    except (ValueError, struct.error, UnicodeDecodeError):
        return None


def parse_cert_public_key(der: bytes, *, label: str, depth: int) -> PublicKey | None:
    """Pull the public key out of a DER certificate."""
    try:
        from cryptography import x509
        from cryptography.hazmat.primitives.asymmetric import dsa, ec, rsa

        cert = x509.load_der_x509_certificate(der)
        key = cert.public_key()
    except Exception:  # noqa: BLE001 — broken DER is data, not a crash
        return None
    if isinstance(key, rsa.RSAPublicKey):
        numbers = key.public_numbers()
        return PublicKey(
            source="tls-chain", label=label, key_type="rsa",
            bits=key.key_size, modulus=numbers.n, depth=depth,
        )
    if isinstance(key, dsa.DSAPublicKey):
        return PublicKey(source="tls-chain", label=label, key_type="dsa",
                         bits=key.key_size, depth=depth)
    if isinstance(key, ec.EllipticCurvePublicKey):
        return PublicKey(source="tls-chain", label=label, key_type="ec",
                         bits=key.curve.key_size, curve=key.curve.name, depth=depth)
    return PublicKey(source="tls-chain", label=label,
                     key_type=type(key).__name__, depth=depth)


# --- scoring -----------------------------------------------------------------


@dataclass(frozen=True)
class KeyVerdict:
    key: PublicKey
    weak_reason: str | None = None
    weak_severity: str | None = None
    roca: bool = False


def score(key: PublicKey) -> KeyVerdict:
    """Judge one public key. Pure."""
    roca = bool(key.key_type == "rsa" and key.modulus and roca_fingerprint(key.modulus))
    reason: str | None = None
    severity: str | None = None
    if key.bits is not None:
        if key.key_type == "rsa" and key.bits < _MIN_RSA_BITS:
            reason = f"RSA {key.bits}-bit"
            severity = "high" if key.bits < 1024 else "medium"
        elif key.key_type == "dsa":
            # DSA in TLS/SSH is capped at 1024 bits in practice and is
            # deprecated outright; size is beside the point.
            reason = f"DSA {key.bits}-bit (deprecated algorithm)"
            severity = "high"
        elif key.key_type == "ec" and key.bits < _MIN_EC_BITS:
            reason = f"EC {key.bits}-bit"
            severity = "high"
    return KeyVerdict(key=key, weak_reason=reason, weak_severity=severity, roca=roca)


def _describe(key: PublicKey) -> str:
    if key.source == "tls-chain":
        return f"certificate at chain depth {key.depth} ({key.label})"
    return f"SSH host key ({key.label})"


# --- persistence -------------------------------------------------------------


def _collect_keys(conn: sqlite3.Connection, scan_id: int) -> dict[tuple[str, int], list[PublicKey]]:
    """Every public key this scan captured, grouped by (ip, port)."""
    per_service: dict[tuple[str, int], list[PublicKey]] = {}

    for ip, port, position, subject, der in conn.execute(
        "SELECT ip, port, position, subject, der FROM chain_certs "
        "WHERE scan_id = ? AND der IS NOT NULL",
        (scan_id,),
    ):
        key = parse_cert_public_key(der, label=subject or "?", depth=position)
        if key is not None:
            per_service.setdefault((ip, port), []).append(key)

    for ip, port, raw in conn.execute(
        "SELECT ip, port, raw FROM services "
        "WHERE scan_id = ? AND service = 'ssh' AND raw IS NOT NULL",
        (scan_id,),
    ):
        for blob_hex in _ssh_key_blobs(raw):
            try:
                blob = bytes.fromhex(blob_hex)
            except ValueError:
                continue
            key = parse_ssh_public_key(blob)
            if key is not None:
                per_service.setdefault((ip, port), []).append(key)

    return per_service


def _ssh_key_blobs(raw) -> list[str]:
    import json

    try:
        parsed = json.loads(raw) if isinstance(raw, str | bytes | bytearray) else raw
    except (ValueError, TypeError):
        return []
    if not isinstance(parsed, dict):
        return []
    out: list[str] = []
    for entry in parsed.get("host_keys") or ():
        if isinstance(entry, dict) and entry.get("blob"):
            out.append(str(entry["blob"]))
    return out


def enrich_key_posture(conn: sqlite3.Connection, scan_id: int) -> tuple[int, int]:
    """Score every captured key. Returns (weak_key_count, roca_count).

    Weak-key verdicts land in `findings`; ROCA hits additionally land in
    `vulns` under its real CVE id.
    """
    per_service = _collect_keys(conn, scan_id)
    if not per_service:
        return 0, 0

    conn.execute(
        "DELETE FROM findings WHERE scan_id = ? AND category = 'weak-key'", (scan_id,)
    )
    conn.execute(
        "DELETE FROM vulns WHERE scan_id = ? AND source = 'keyposture'", (scan_id,)
    )

    weak_count = 0
    roca_count = 0
    import json

    for (ip, port), keys in per_service.items():
        for verdict in (score(k) for k in keys):
            if verdict.weak_reason:
                conn.execute(
                    "INSERT INTO findings (scan_id, ip, port, category, severity, title, detail) "
                    "VALUES (?, ?, ?, 'weak-key', ?, ?, ?)",
                    (
                        scan_id, ip, port, verdict.weak_severity,
                        f"Weak public key: {verdict.weak_reason} on "
                        f"{_describe(verdict.key)}.",
                        json.dumps({
                            "source": verdict.key.source,
                            "key_type": verdict.key.key_type,
                            "bits": verdict.key.bits,
                            "curve": verdict.key.curve,
                            "depth": verdict.key.depth,
                        }),
                    ),
                )
                weak_count += 1
            if verdict.roca:
                conn.execute(
                    "INSERT INTO findings (scan_id, ip, port, category, severity, title, detail) "
                    "VALUES (?, ?, ?, 'weak-key', 'high', ?, ?)",
                    (
                        scan_id, ip, port,
                        f"ROCA fingerprint matches on {_describe(verdict.key)} "
                        f"(Infineon RSALib key generation).",
                        json.dumps({
                            "cve": ROCA_CVE,
                            "source": verdict.key.source,
                            "bits": verdict.key.bits,
                        }),
                    ),
                )
                conn.execute(
                    "INSERT INTO vulns (scan_id, ip, port, cve, cpe, confidence, source) "
                    "VALUES (?, ?, ?, ?, NULL, ?, 'keyposture')",
                    # Below 1.0 on purpose: the fingerprint is a necessary
                    # condition for RSALib generation, not a factorization.
                    (scan_id, ip, port, ROCA_CVE, 0.9),
                )
                roca_count += 1
    return weak_count, roca_count
